In [6]:
import pandas as pd
import requests

markets = requests.get('https://ftx.com/api/markets').json()
df = pd.DataFrame(markets['result1'])
df.set_index('name', inplace = True)
df.T

KeyError: 'result1'

In [4]:
markets = pd.DataFrame(requests.get('https://ftx.com/api/markets/BTC/USD').json())
markets = markets.drop(['success'], axis=1)
markets

                                result
ask                            18719.0
baseCurrency                       BTC
bid                            18718.0
change1h                     -0.002558
change24h                    -0.063632
changeBod                    -0.019692
enabled                           True
futureType                        None
highLeverageFeeExempt             True
isEtfMarket                      False
largeOrderThreshold             2400.0
last                           18718.0
minProvideSize                  0.0001
name                           BTC/USD
postOnly                         False
price                          18718.0
priceHigh24h                   20387.0
priceIncrement                     1.0
priceLow24h                    18464.0
quoteCurrency                      USD
quoteVolume24h         1061322250.0993
restricted                       False
sizeIncrement                   0.0001
type                              spot
underlying                        None
volumeUsd24h           1061322250.0993

In [9]:
historical = requests.get('https://ftx.com/api/markets/BTC/USD/candles?resolution=3600&start_time=1609462800').json()
historical = pd.DataFrame(historical['result'])
historical.drop(['startTime'], axis = 1, inplace=True)
historical.head()

           time     open     high      low    close        volume
0  1.658945e+12  21631.0  22779.0  21631.0  22584.0  2.109490e+08
1  1.658948e+12  22584.0  23121.0  22574.0  22780.0  1.056963e+08
2  1.658952e+12  22781.0  22920.0  22680.0  22788.0  3.059635e+07
3  1.658956e+12  22788.0  22801.0  22591.0  22682.0  1.972514e+07
4  1.658959e+12  22683.0  22967.0  22659.0  22882.0  3.561042e+07

In [10]:
historical = requests.get('https://ftx.com/api/markets/BTC/USD/candles?resolution=3600&start_time=1609462800').json()
historical = pd.DataFrame(historical['result'])
historical.drop(['startTime'], axis = 1, inplace=True)
historical.head()

           time     open     high      low    close        volume
0  1.658945e+12  21631.0  22779.0  21631.0  22584.0  2.109490e+08
1  1.658948e+12  22584.0  23121.0  22574.0  22780.0  1.056963e+08
2  1.658952e+12  22781.0  22920.0  22680.0  22788.0  3.059635e+07
3  1.658956e+12  22788.0  22801.0  22591.0  22682.0  1.972514e+07
4  1.658959e+12  22683.0  22967.0  22659.0  22882.0  3.561042e+07

In [11]:
historical['time'] = pd.to_datetime(historical['time'], unit='ms')
historical.set_index('time', inplace=True)
historical['20 SMA'] = historical.close.rolling(20).mean()
historical.tail()

,open,high,low,close,volume,20 SMA
time,,,,,,
2022-09-28 01:00:00,19092.0,19144.0,18938.0,19002.0,4.610762e+07,19616.95
2022-09-28 02:00:00,19001.0,19009.0,18464.0,18630.0,8.918132e+07,19538.60
2022-09-28 03:00:00,18630.0,18772.0,18621.0,18743.0,2.196899e+07,19466.55
2022-09-28 04:00:00,18743.0,18825.0,18714.0,18761.0,1.575195e+07,19397.35
2022-09-28 05:00:00,18761.0,18809.0,18652.0,18804.0,2.376629e+07,19328.45